require 'simplecov'
SimpleCov.start
require 'faraday'
require 'minitest'
require 'minitest/autorun'
require 'minitest/pride'
require 'pry'
require './lib/controller'
require './lib/date_controller'
require './lib/debug_controller'
require './lib/diagnostic'
require './lib/game_controller'
require './lib/hello_controller'
require './lib/response_code'
require './lib/router'
require './lib/shutdown_controller'
require './lib/word_search_controller'
require './lib/web_server'
